"""add agency country

Revision ID: ebfefbe6baf0
Revises: 0001_init
Create Date: 2018-04-10 21:42:21.843603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_agency_country'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('country', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency', 'country')
    # ### end Alembic commands ###
