"""empty message

Revision ID: eeb74621f581
Revises: 0002_add_fb_id
Create Date: 2018-02-26 20:28:48.976301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_rename_fb_id_fbId'
down_revision = '0002_add_fb_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fbId', sa.Text(), nullable=True))
    op.drop_constraint('user_fb_id_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['fbId'])
    op.drop_column('user', 'fb_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fb_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_fb_id_key', 'user', ['fb_id'])
    op.drop_column('user', 'fbId')
    # ### end Alembic commands ###
