"""change rent from monthly to weekly

Revision ID: f11b88bf7b68
Revises: 0002_agency_country
Create Date: 2018-04-11 23:25:35.612416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003_rent_to_weekly'
down_revision = '0002_agency_country'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('weeklyRent', sa.Float(), nullable=True))
    op.drop_column('review', 'monthlyRent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('monthlyRent', postgresql.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=True))
    op.drop_column('review', 'weeklyRent')
    # ### end Alembic commands ###
