"""Added profile picture

Revision ID: 223b8414daff
Revises: 0003_rename_fb_id_fbId
Create Date: 2018-03-11 19:30:25.080599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004_added_profile_picture'
down_revision = '0003_rename_fb_id_fbId'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profilePicture', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilePicture')
    # ### end Alembic commands ###
