"""add domain ids

Revision ID: cda43a18d9ca
Revises: 0005_update_properties
Create Date: 2018-04-19 23:14:16.807627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda43a18d9ca'
down_revision = '0005_update_properties'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('domainId', sa.Text(), nullable=True))
    op.add_column('agent', sa.Column('domainId', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'domainId')
    op.drop_column('agency', 'domainId')
    # ### end Alembic commands ###
